### ISSUE TITLE
Issue with osx url 

### ISSUE THREAD

**Issue by razorsk8jz** [virtualstaticvoid/asdf-istioctl#1]
when using asdf-istioctl to try and install istio on osx the wrong location is coming back causing an error trying to install.

Downloading istioctl from https://github.com/istio/istio/releases/download/1.9.2/istio-1.9.2-osx-amd64.tar.gz

This is the incorrect url as it is adding -amd64 to the url

https://github.com/istio/istio/releases/download/1.9.2/istio-1.9.2-osx.tar.gz
^ should be the correct url

**Comment by virtualstaticvoid** [comment]
Hi @razorsk8jz 
I suspect you have an older version of this plugin since this was fixed in b71f171.
You can run `asdf plugin-update istioctl` to get the latest version.

**Comment by razorsk8jz** [comment]
Please see results from your response below 

$ asdf plugin update istioctl
Updating istioctl...
Already on 'master'
Your branch is up to date with 'origin/master'.

$ asdf install istioctl 1.9,2
Downloading istioctl from https://github.com/istio/istio/releases/download/1.9,2/istio-1.9,2-osx-amd64.tar.gz
bin_install_path: /Users/****/.asdf/installs/istioctl/1.9,2/bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     25      0 --:--:-- --:--:-- --:--:--    25
tar: Error opening archive: Unrecognized archive format
$ 

it shows that i'm already on master and up to date - if you need any more information please let me know

**Comment by virtualstaticvoid** [comment]
Hi @razorsk8jz 

I can't figure out how this is failing, since the logic to determine [platform](https://github.com/virtualstaticvoid/asdf-istioctl/blob/master/bin/install#L26) yields `osx` correctly, whereas the logic for the [architecture](https://github.com/virtualstaticvoid/asdf-istioctl/blob/master/bin/install#L31) is not, but they basically perform the same check, and the [build](https://github.com/virtualstaticvoid/asdf-istioctl/runs/1705885862?check_suite_focus=true) for Mac is passing.

Would you mind running `asdf plugin-list --urls` and check that the entry for `istioctl` is indeed `https://github.com/virtualstaticvoid/asdf-istioctl.git`, as I'm wondering whether you might have a different plugin, such as `https://github.com/rafik8/asdf-istioctl` which is currently [failing](https://travis-ci.org/github/rafik8/asdf-istioctl).

Thanks

**Comment by virtualstaticvoid** [comment]
Okay, seems I've managed to replicate it with [this build](https://github.com/virtualstaticvoid/asdf-istioctl/runs/2336768654?check_suite_focus=true).

**Comment by virtualstaticvoid** [comment]
Reverted the change and it [passes](https://github.com/virtualstaticvoid/asdf-istioctl/runs/2336819223?check_suite_focus=true).
I go back to my previous assumption that you have a different plugin.
